<?php

namespace Tests\Feature\Services;

use Tests\TestCase;
use App\Models\Lead;
use App\Models\Proposal;
use App\Services\Proposal\ProposalGenerationService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Services\AI\OpenAIClientInterface;
use Mockery;

class ProposalGenerationServiceTest extends TestCase
{
    use RefreshDatabase;

    public function test_it_generates_a_proposal_for_a_lead(): void
    {
        $lead = Lead::factory()->create();

        // Mock the OpenAI client
        $mockClient = Mockery::mock(OpenAIClientInterface::class);
        $mockClient->shouldReceive('chat')->andReturn('Sample proposal content generated by AI.');
        
        $this->app->instance(OpenAIClientInterface::class, $mockClient);

        $service = app(ProposalGenerationService::class);
        $proposal = $service->generate($lead);

        $this->assertInstanceOf(Proposal::class, $proposal);
        $this->assertEquals($lead->id, $proposal->lead_id);
        $this->assertNotEmpty($proposal->content);
    }
}
