<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('proposals', function (Blueprint $table) {
            $table->id();
            $table->foreignId('opportunity_id')->nullable()->constrained('opportunities')->nullOnDelete();
            $table->foreignId('lead_id')->nullable()->constrained('leads')->nullOnDelete();
            $table->longText('content');
            $table->boolean('generated_by_ai');
            $table->enum('status', ['draft', 'sent', 'viewed', 'accepted', 'rejected', 'expired'])->default('draft');
            $table->timestamp('sent_at')->nullable();
            $table->timestamp('viewed_at')->nullable();
            $table->timestamp('accepted_at')->nullable();
            $table->timestamp('rejected_at')->nullable();
            $table->timestamp('expires_at')->nullable();
            $table->json('metadata')->nullable();
            $table->timestamps();
            $table->softDeletes();

            $table->index(['opportunity_id']);
            $table->index(['lead_id']);
            $table->index(['status']);

            // Foreign key indexes
            $table->index('lead_id', 'idx_proposals_lead_id');
            
            // Status filtering
            $table->index('status', 'idx_proposals_status');
            
            // Generated by AI flag
            $table->index('generated_by_ai', 'idx_proposals_generated_by_ai');
            
            // Date queries
            $table->index('created_at', 'idx_proposals_created_at');
            
            // Recent AI-generated proposals
            $table->index(['generated_by_ai', 'created_at'], 'idx_proposals_ai_created');
            
            // Soft deletes
            $table->index('deleted_at', 'idx_proposals_deleted_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('proposals');
    }
};
