<?php

namespace Tests\Unit;

use App\Events\LeadDocumentProcessed;
use App\Jobs\ProcessLeadDocument;
use App\Models\Lead;
use App\Models\LeadDocument;
use App\Services\AI\OpenAIClient;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Event;
use Tests\TestCase;

class ProcessLeadDocumentTest extends TestCase
{
    use RefreshDatabase;

    public function test_job_generates_summary_and_broadcasts()
    {
        Event::fake();

        $lead = Lead::factory()->create();

        $document = LeadDocument::create([
            'lead_id' => $lead->id,
            'original_name' => 'sample.txt',
            'filename' => 'sample.txt',
            'storage_path' => 'lead_documents/sample.txt',
            'mime_type' => 'text/plain',
            'extracted_text' => ['text' => "This is a test document. It has several sentences to summarize."],
            'status' => LeadDocument::STATUS_QUEUED ?? 'queued',
        ]);

        // Create a mock OpenAIClient
        $mock = \Mockery::mock(OpenAIClient::class);
        $mock->shouldReceive('generate')->once()->andReturn('A concise summary generated by AI.');
        $this->app->instance(OpenAIClient::class, $mock);

        $job = new ProcessLeadDocument($document->id);

        // Run the job handler directly (DocumentParserService is not used because extracted_text exists)
        $job->handle(app()->make('\App\Services\DocumentParserService'), app()->make(OpenAIClient::class));

        $document->refresh();

        $this->assertEquals(LeadDocument::STATUS_SUCCEEDED ?? 'succeeded', $document->status);
        $this->assertIsArray($document->ai_summary);
        $this->assertStringContainsString('concise summary', strtolower($document->ai_summary['summary']));

        Event::assertDispatched(LeadDocumentProcessed::class, function ($e) use ($document) {
            return $e->document->id === $document->id && in_array($e->status, [LeadDocument::STATUS_SUCCEEDED ?? 'succeeded', LeadDocument::STATUS_FAILED ?? 'failed']);
        });
    }
}
